// @ts-nocheck
import JSZip from 'jszip';
import { calculateReport, dateCheck, period, id, stamp, fail, recordKinds } from './domain';
import { storage, resolveMember, configAndSeed, allRecords, roles, scope, publicMember, saveAtomic, expectRevision, keyFor, recordSQL, auditSQL } from './store';
import { inspectDocument, reportPack, archive } from './reports';
const lines=['Personnel Emoluments','Goods & Services','Development / PIP','Other'];
const int=(v,label)=>{const n=Number(v);if(!Number.isInteger(n)||n<0)fail(label+' must be a nonnegative whole number.');return n};
const amount=(v)=>{const n=Number(v);if(!Number.isFinite(n)||n<0)fail('Enter a nonnegative amount.');return n};
const text=(v)=>String(v??'').trim();
const clean=(p)=>Object.fromEntries(Object.entries(p).filter(([k,v])=>!['_key','revision','data','blob_key','expected_revision','case_revision','approved_by','approved_at','entered_by','entered_by_id','at','officer_id'].includes(k)));
const decode=s=>{if(typeof s!=='string'||!/^[A-Za-z0-9+/]*={0,2}$/.test(s))fail('Invalid file data.');return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
const bytes64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.slice(i,i+8192));return btoa(s)};
const j=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const download=(bytes,name,mime)=>new Response(bytes,{headers:{'Content-Type':mime,'Content-Disposition':`attachment; filename="${name.replace(/[^A-Za-z0-9_. -]/g,'_')}"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
export async function handleApplication(request,identity){
 let blobAdded=null,bucket;try{
 const st=storage(),db=st.db;bucket=st.bucket;const u=await resolveMember(db,identity),config=await configAndSeed(db,bucket,u),url=new URL(request.url),action=url.pathname.split('/').at(-1),qs=url.searchParams;
 if(request.method==='GET'){
  let unit=qs.get('unit')||u.unit;scope(u,unit,true);
  if(action==='state'){
   const records=await allRecords(db,u.role==='admin'||u.role==='reporting'?null:u.unit),members=(await db.prepare('SELECT * FROM members ORDER BY name').all()).results;
   for(const kind of recordKinds){if(u.role==='officer'){if(kind==='case')records[kind]=records[kind].filter(x=>x.officer_id===u.id);else if(kind==='event')records[kind]=records[kind].filter(x=>x.entered_by_id===u.id||records.case.some(c=>c.id===x.case_id));else if(['expense','budget','note','audit','snapshot'].includes(kind))records[kind]=[]}if(['finance','reporting'].includes(u.role)&&['case','event','audit'].includes(kind))records[kind]=[];for(const x of records[kind]){delete x.data;delete x.blob_key;}}
   return j({user:publicMember(u),config,users:members.filter(x=>u.role==='admin'||x.unit===u.unit||u.role==='reporting').map(x=>u.role==='admin'?publicMember(x):{id:x.id,name:x.name,role:x.role,unit:x.unit,active:!!x.active}),records});
  }
  if(['report','export'].includes(action)){roles(u,['registry','manager','finance','reporting']);const records=await allRecords(db,unit==='ALL'?null:unit),r=calculateReport(config,records,unit,qs.get('year')||2026,qs.get('quarter')||1);return action==='report'?j(r):download(await reportPack(config,records,r,bucket),`DLIR_${unit}_${r.year}_${r.period}.zip`,'application/zip')}
  if(['document','snapshot'].includes(action)){if(action==='snapshot')roles(u,['manager','reporting']);const row=await db.prepare('SELECT payload FROM records WHERE key = ?').bind(action+':'+qs.get('id')).first();if(!row)fail('File not found.');const d=JSON.parse(row.payload);scope(u,d.unit,true);const blob=await bucket.get(d.blob_key);if(!blob)fail('This file is temporarily unavailable.');return download(await blob.arrayBuffer(),d.name||`DLIR_approved_${d.year}_${d.quarter===0?'Annual':'Q'+d.quarter}.zip`,blob.httpMetadata?.contentType||'application/octet-stream')}
  if(action==='csv'){roles(u,['manager','registry','finance']);const kind=qs.get('kind');if(!['case','event','expense','workplan'].includes(kind)||u.role==='finance'&&!['expense','workplan'].includes(kind))fail('Your role cannot export this data.');const rs=(await allRecords(db,unit==='ALL'?null:unit))[kind],keys=Array.from(new Set(rs.flatMap(x=>Object.keys(x)))).filter(k=>!k.startsWith('_'));const cell=x=>'"'+String(typeof x==='object'?JSON.stringify(x):x??'').replaceAll('"','""').replace(/^[=+@-]/,"'$&")+'"';return download('\ufeff'+[keys,...rs.map(x=>keys.map(k=>x[k]))].map(r=>r.map(cell).join(',')).join('\r\n'),kind+'.csv','text/csv;charset=utf-8')}
  if(action==='backup'){roles(u,[]);const records=await allRecords(db),members=(await db.prepare('SELECT * FROM members ORDER BY name').all()).results,z=new JSZip(),total=records.document.concat(records.snapshot).reduce((n,d)=>n+(d.size||0),0);if(total>20*1024*1024)fail('Attachments exceed the 20 MB backup limit. Export records as CSV and download documents individually, or contact ICT for a full storage backup.');z.file('DLIR_cloud_register.json',JSON.stringify({format:'DLIR_CLOUD_REGISTER',version:1,exported_at:stamp(),config,records,members:members.map(publicMember)}));for(const d of [...records.document,...records.snapshot]){const blob=await bucket.get(d.blob_key);if(!blob)fail('A stored document is unavailable; the backup was not completed.');z.file('attachments/'+d.id,new Uint8Array(await blob.arrayBuffer()))}return download(await z.generateAsync({type:'uint8array',compression:'DEFLATE'}),`DLIR_cloud_backup_${stamp().slice(0,10)}.zip`,'application/zip')}
  fail('Unknown request.');
 }
 if(request.method!=='POST')return j({error:'Method not allowed.'},405);
 const origin=request.headers.get('origin');if(origin&&origin!==url.origin)throw Object.assign(Error('Cross-origin request rejected.'),{status:403});if(!request.headers.get('content-type')?.startsWith('application/json'))fail('JSON request required.');if(Number(request.headers.get('content-length')||0)>15*1024*1024)fail('Request exceeds the upload limit.');const body=await request.text();if(body.length>15*1024*1024)fail('Request exceeds the upload limit.');const input=JSON.parse(body),unit=input.unit||u.unit;scope(u,unit,['note','snapshot'].includes(action)&&unit==='ALL');if(!config.units.some(x=>x.id===unit)&&!(['upload','note','snapshot'].includes(action)&&unit==='ALL'))fail('Select a valid organisational unit.');const p={...clean(input),unit};const records=await allRecords(db,unit==='ALL'?null:unit),members=(await db.prepare('SELECT * FROM members').all()).results;
 if(action==='member'){
  roles(u,[]);if(!['admin','manager','registry','officer','finance','reporting'].includes(p.role))fail('Select a valid access role.');if(!config.units.some(x=>x.id===p.account_unit))fail('Select a staff unit.');if(p.id&&!/^[a-f0-9]{32}$/.test(p.id))fail('Invalid staff account ID.');const memberId=p.id||id(),old=members.find(x=>x.id===memberId);if(old?.id===u.id)fail('Your own administrator access cannot be changed here.');const email=text(p.email).toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('Enter a valid sign-in email.');if(!text(p.name))fail('Enter the staff member’s name.');const active=p.active==='No'||p.active===false?0:1;const duplicate=members.find(x=>x.id!==memberId&&(email&&x.email===email||x.name===text(p.name)&&x.unit===p.account_unit));if(duplicate)fail('An account with this email or staff name already exists.');
  const statement=db.prepare("INSERT INTO members (id,user_id,email,name,role,unit,active,created_at) VALUES (?,NULL,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name,role=excluded.role,unit=excluded.unit,active=excluded.active WHERE (members.user_id IS NULL OR (members.name=excluded.name AND members.email=excluded.email AND members.unit=excluded.unit)) AND (members.role != 'admin' OR (excluded.role = 'admin' AND excluded.active = 1) OR (SELECT COUNT(*) FROM members WHERE role = 'admin' AND active = 1) > 1)");const res=await db.batch([statement.bind(memberId,email||null,text(p.name),p.role,p.account_unit,active,old?.created_at||stamp()),auditSQL(db,u,'Configure staff access',memberId,p.account_unit)]);if(!res[0].meta.changes)fail('Linked names, email and unit cannot be changed; the last administrator must remain active.');return j({ok:true});
 }
 if(action==='import'){roles(u,[]);return await importOffline(db,bucket,u,input,config)}
 if(action==='case'){
  roles(u,['registry','manager']);dateCheck(p.registered);p.reference=text(p.reference);p.employer=text(p.employer);if(!p.reference||!p.employer)fail('Reference and employer are required.');if(!config.categories.includes(p.category)||!['Industrial matter','Industrial dispute'].includes(p.nature))fail('Select a valid matter classification.');p.workers=int(p.workers,'Workers affected');if(p.workers<1)fail('Workers affected must be at least one.');Object.assign(p,{id:id(),status:'Registered',officer:'',officer_id:'',at:stamp(),entered_by:u.name,entered_by_id:u.id});await saveAtomic(db,u,'case',p,{uniqueKey:'case:'+unit+':'+p.reference.toLowerCase()});
 }else if(action==='event'){
  roles(u,['registry','manager','officer']);dateCheck(p.date);if(p.due)dateCheck(p.due);if(!config.events.includes(p.type))fail('Select a valid event type.');const c=records.case.find(x=>x.id===p.case_id),expected=c?.revision;if(p.case_id&&!c)fail('Unknown case.');if(['Assignment','Closed','Reopened'].includes(p.type)&&!c)fail('Select a case for this event.');if(c&&Number(input.case_revision)!==c.revision)throw Object.assign(Error('This case changed. Refresh before adding the next event.'),{status:409});p.quantity=amount(p.quantity);if(p.workplan_id&&!records.workplan.some(w=>w.id===p.workplan_id&&w.year===Number(p.date.slice(0,4))))fail('Select a workplan for the event year.');let uniqueKey=null;
  if(p.type==='Compulsory conference completed'){p.evidence=text(p.evidence);if(p.quantity!==1||!p.evidence||!p.workplan_id)fail('Record one completed conference with unique evidence and a workplan link.');uniqueKey='conference:'+unit+':'+p.evidence.toLowerCase()}
  if(c){if(u.role==='officer'&&c.officer_id!==u.id)fail('Only the assigned case officer may update this matter.');if(p.date<c.registered||records.event.some(x=>x.case_id===c.id&&x.date>p.date))fail('Record case events in date order after registration.');if(p.type==='Reopened'){roles(u,['registry','manager']);if(c.status!=='Closed')fail('Only a closed matter may be reopened.');p.status=c.officer_id?'Assigned':'Registered'}else{if(c.status==='Closed')fail('Reopen this matter before adding further actions.');if(p.type==='Assignment'){roles(u,['registry','manager']);const owner=members.find(x=>x.id===p.officer&&x.unit===unit&&x.active);if(!owner)fail('Select an active officer in this unit.');p.officer=owner.name;p.officer_id=owner.id;p.status='Assigned';c.officer=owner.name;c.officer_id=owner.id}else if(p.type==='Closed'){if(!text(p.evidence)||!text(p.narrative))fail('Closure requires an outcome and evidence.');p.status='Closed'}else if(p.status&&!config.statuses.filter(x=>x!=='Closed').includes(p.status))fail('Use the Closed event to close a matter.')}if(p.status)c.status=p.status;if(p.next_action)c.next_action=p.next_action;if(p.due)c.due=p.due;if(p.type!=='Assignment'){p.officer=c.officer;p.officer_id=c.officer_id}}
  Object.assign(p,{id:id(),at:stamp(),entered_by:u.name,entered_by_id:u.id,approved:false});await saveAtomic(db,u,'event',p,{uniqueKey,caseUpdate:c?{record:c,expected}:null});
 }else if(action==='approve'){
  roles(u,['manager']);if(!['event','expense'].includes(p.kind))fail('Invalid approval type.');const old=records[p.kind].find(x=>x.id===p.id);if(!old)fail('Record not found.');const expected=expectRevision(input,old);Object.assign(old,{approved:true,approved_by:u.name,approved_by_id:u.id,approved_at:stamp()});await saveAtomic(db,u,p.kind,old,{expected});
 }else if(action==='expense'){
  roles(u,['finance','manager']);dateCheck(p.date);p.amount=amount(p.amount);p.voucher=text(p.voucher);if(!p.voucher||!lines.includes(p.budget_line))fail('Enter a voucher line and budget line.');Object.assign(p,{id:id(),at:stamp(),entered_by:u.name,entered_by_id:u.id,approved:false});await saveAtomic(db,u,'expense',p,{uniqueKey:'expense:'+unit+':'+p.voucher.toLowerCase()});
 }else if(['budget','note','workplan'].includes(action)){
  roles(u,action==='budget'?['finance','manager']:action==='note'?['manager','registry','reporting']:['manager']);p.year=int(p.year,'Reporting year');if(action!=='workplan'){p.quarter=int(p.quarter,'Quarter');period(p.year,p.quarter)}else period(p.year,0);
  if(action==='budget'){if(!lines.includes(p.budget_line))fail('Select a budget line.');p.appropriation=amount(p.appropriation);p.released=amount(p.released)}
  if(action==='note'){if(u.role==='reporting'&&unit!=='ALL')fail('Reporting staff edit the Department consolidation narrative.');if(unit==='ALL'&&p.workplan_id)fail('Department narratives use the summary fields.');if(p.ontrack==='No'&&!text(p.justification))fail('Explain why the activity is off track.');if(p.workplan_id&&!records.workplan.some(x=>x.id===p.workplan_id&&x.year===p.year))fail('Select a workplan for this year.')}
  if(action==='workplan'){dateCheck(p.due);p.id=text(p.id);if(!p.id||!text(p.activity)||!text(p.indicator))fail('Workplan ID, activity and indicator are required.');p.kfas=String(p.kfas||'').split(',').filter(x=>text(x)).map(Number);if(p.kfas.some(x=>!Number.isInteger(x)||x<1||x>8))fail('KFA links must be numbers 1–8.');for(const k of ['annual_target','quarter_target'])p[k]=p[k]===''||p[k]===null?null:amount(p[k])}
  const old=records[action].find(x=>keyFor(action,x)===keyFor(action,p)),expected=expectRevision(input,old);await saveAtomic(db,u,action,p,{expected});
 }else if(action==='staff_return'){
  roles(u,['manager']);dateCheck(p.date);if(!text(p.division))fail('Enter a division.');for(const k of ['ceiling','strength','casual','unattached','vehicles'])p[k]=int(p[k],k);if(p.strength>p.ceiling)fail('Staff on strength exceeds the approved ceiling.');Object.assign(p,{id:id(),at:stamp(),vacant:p.ceiling-p.strength});await saveAtomic(db,u,action,p);
 }else if(['alignment','kpi'].includes(action)){
  roles(u,['manager']);if(p.effective_start)dateCheck(p.effective_start);if(p.effective_end)dateCheck(p.effective_end);if(p.effective_start&&p.effective_end&&p.effective_end<p.effective_start)fail('Effective end precedes start.');if(action==='alignment'&&!records.document.some(x=>x.id===p.document_id))fail('Select a source document.');if(p.workplan_id&&!records.workplan.some(x=>x.id===p.workplan_id))fail('Select a valid workplan.');Object.assign(p,{id:id(),at:stamp()});await saveAtomic(db,u,action,p);
 }else if(action==='upload'){
  roles(u,['manager']);const raw=decode(input.data);p.name=text(p.name).replace(/[\\/]/g,'_');if(!p.name||p.name.length>180||!['reference','summary','table5','table51'].includes(p.kind))fail('Enter a valid document name and purpose.');if(p.effective)dateCheck(p.effective);const extracted=await inspectDocument(raw,p.name,p.kind),docId=id(),blob_key='documents/'+unit+'/'+docId,sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',raw)),x=>x.toString(16).padStart(2,'0')).join('');await bucket.put(blob_key,raw,{httpMetadata:{contentType:p.name.endsWith('.docx')?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/octet-stream'}});blobAdded=blob_key;Object.assign(p,{id:docId,at:stamp(),blob_key,size:raw.length,extracted,sha256,version:1+records.document.filter(x=>x.name===p.name&&x.kind===p.kind).length});await saveAtomic(db,u,'document',p,{uniqueKey:'document:'+unit+':'+p.kind+':'+p.name+':'+p.version});blobAdded=null;
 }else if(action==='snapshot'){
  roles(u,['manager','reporting']);if(u.role==='reporting'&&unit!=='ALL')fail('Reporting staff approve the Department consolidation report.');const r=calculateReport(config,records,unit,p.year,p.quarter);if(r.reconciliation!==0)fail('The case register does not reconcile.');if(!text(p.review_note))fail('Record the registry and finance reconciliation review.');const bytes=await reportPack(config,records,r,bucket),snapshotId=id(),blob_key='reports/'+snapshotId+'.zip';await bucket.put(blob_key,bytes,{httpMetadata:{contentType:'application/zip'}});blobAdded=blob_key;await saveAtomic(db,u,'snapshot',{id:snapshotId,unit,year:r.year,quarter:r.quarter,approved_by:u.name,approved_by_id:u.id,at:stamp(),review_note:p.review_note,report:r,blob_key,size:bytes.length});blobAdded=null;
 }else fail('Unknown action.');return j({ok:true});
 }catch(e){if(blobAdded&&bucket)await bucket.delete(blobAdded).catch(()=>{});console.error('DLIR request failed',e?.message);let message=e?.message||'The request could not be completed.';if(/UNIQUE constraint/i.test(message))message='This reference, voucher line or evidence is already recorded.';else if(/D1_|SQLITE_|R2_|binding|no such table|database|timeout/i.test(message))message='Departmental storage is temporarily unavailable. Your entry has not been saved; please try again.';return j({error:message},e?.status||400)}
}
async function importOffline(db,bucket,u,input,config){
 const current=await allRecords(db);if(current.case.length||current.event.length||current.expense.length||current.snapshot.length)fail('Import is available only before live case, event, expenditure or approved report records have been entered.');const bytes=decode(input.data);if(bytes.length>10*1024*1024)fail('Import ZIP exceeds 10 MB.');const z=await archive(bytes),f=z.file('DLIR_register.json');if(!f)fail('Choose a backup from the no-install DLIR Browser Register.');const v=JSON.parse(await f.async('string'));if(v.format!=='DLIR_BROWSER_REGISTER'||v.version!==1)fail('Unsupported backup format.');for(const k of recordKinds)if(!Array.isArray(v.records?.[k]))fail('Incomplete backup: '+k);if(Object.values(v.records).reduce((n,x)=>n+x.length,0)>1000)fail('This import exceeds 1,000 records. Contact ICT for a bulk migration.');const existingMembers=(await db.prepare('SELECT * FROM members').all()).results,memberMap=new Map(),statements=[],createdBlobs=[];let total=0;
 try{
 for(const staff of v.staff||[]){if(!config.units.some(x=>x.id===staff.unit)||!text(staff.name))fail('Invalid officer directory in backup.');const existing=existingMembers.find(x=>x.unit===staff.unit&&x.name===staff.name),memberId=existing?.id||id();memberMap.set(staff.unit+':'+staff.name,memberId);if(!existing)statements.push(db.prepare("INSERT INTO members (id,user_id,email,name,role,unit,active,created_at) VALUES (?,NULL,NULL,?,'officer',?,1,?)").bind(memberId,staff.name,staff.unit,stamp()))}
 for(const kind of recordKinds.filter(k=>k!=='audit'))for(const source of v.records[kind]){const p={...source};delete p._key;delete p.revision;if(!config.units.some(x=>x.id===p.unit)&&!(kind==='document'&&p.unit==='ALL'))fail('Invalid unit in imported data.');if(!['workplan','note','budget'].includes(kind)&&!/^[a-f0-9]{32}$/.test(p.id))fail('Invalid record ID in backup.');if(kind==='case'){dateCheck(p.registered);if(!config.categories.includes(p.category)||!config.statuses.includes(p.status))fail('Invalid case classification.');p.officer_id=memberMap.get(p.unit+':'+p.officer)||''}if(kind==='event'){dateCheck(p.date);if(!config.events.includes(p.type))fail('Invalid event type.');p.quantity=amount(p.quantity);p.officer_id=memberMap.get(p.unit+':'+p.officer)||''}if(kind==='expense'){dateCheck(p.date);p.amount=amount(p.amount)}if(['document','snapshot'].includes(kind)){const raw=decode(p.data);total+=raw.length;if(total>20*1024*1024)fail('Imported attachments exceed 20 MB.');if(kind==='document')await inspectDocument(raw,p.name,p.kind);const blob_key='imports/'+id();await bucket.put(blob_key,raw);createdBlobs.push(blob_key);delete p.data;p.blob_key=blob_key;p.size=raw.length}if(kind==='workplan'){p.year=Number(p.year);period(p.year,0);if(!Array.isArray(p.kfas)||!text(p.activity))fail('Invalid workplan.')}const existing=current[kind].find(x=>keyFor(kind,x)===keyFor(kind,p));const uniqueKey=kind==='case'?'case:'+p.unit+':'+text(p.reference).toLowerCase():kind==='expense'?'expense:'+p.unit+':'+text(p.voucher).toLowerCase():kind==='event'&&p.type==='Compulsory conference completed'?'conference:'+p.unit+':'+text(p.evidence).toLowerCase():null;statements.push(recordSQL(db,kind,p,existing?.revision??null,uniqueKey))}
 statements.push(auditSQL(db,u,'Import offline backup','Imported '+statements.length+' rows','P3'));await db.batch(statements);return j({ok:true,imported:statements.length-1});
 }catch(e){await Promise.all(createdBlobs.map(k=>bucket.delete(k).catch(()=>{})));throw e}
}
