// @ts-nocheck
import JSZip from 'jszip';
import { xml2js, js2xml } from 'xml-js';
import { fail, reportTokens } from './domain';
const localName=n=>n?.split(':').at(-1);
function descendants(root,name){let result=[];for(const e of root.elements||[]){if(e.type==='element'&&localName(e.name)===name)result.push(e);result.push(...descendants(e,name))}return result}
const textOf=t=>(t.elements||[]).filter(x=>x.type==='text').map(x=>x.text).join('');
const setText=(t,s)=>{t.elements=[{type:'text',text:s}];t.attributes={...t.attributes,'xml:space':'preserve'}};
export async function archive(raw){const z=await JSZip.loadAsync(raw);let size=0;for(const [name,f] of Object.entries(z.files)){size+=f._data?.uncompressedSize||0;if(size>30*1024*1024||/vbaproject/i.test(name))fail('The document is too large when expanded, or contains macros.')}return z}
export async function inspectDocument(raw,name,kind){const ext=name.split('.').at(-1).toLowerCase();if(!['docx','xlsx','pdf','json'].includes(ext)||raw.length>10*1024*1024)fail('Upload DOCX, XLSX, PDF or JSON up to 10 MB.');if(kind!=='reference'&&ext!=='docx')fail('Report templates must be DOCX with mapped fields.');let extracted='';if(['docx','xlsx'].includes(ext)){const z=await archive(raw);if(ext==='docx'){const f=z.file('word/document.xml');if(!f)fail('Invalid Word document.');const tree=xml2js(await f.async('string'),{compact:false});extracted=descendants(tree,'p').map(p=>descendants(p,'t').map(textOf).join('')).join('\n');if(kind!=='reference'&&!['UNIT','YEAR','PERIOD'].every(k=>extracted.includes('{{'+k+'}}')))fail('The Word template needs {{UNIT}}, {{YEAR}} and {{PERIOD}}.');extracted=extracted.slice(0,40000)}}else if(ext==='json')JSON.parse(new TextDecoder().decode(raw));return extracted}
export async function fillWord(raw,values){const z=await archive(raw);for(const [name,f] of Object.entries(z.files))if(name.startsWith('word/')&&name.endsWith('.xml')&&!f.dir){const xml=await f.async('string');if(!xml.includes('{{'))continue;const tree=xml2js(xml,{compact:false});let changed=false;for(const p of descendants(tree,'p')){const ts=descendants(p,'t'),full=ts.map(textOf).join(''),starts=[];let offset=0;for(const t of ts){starts.push(offset);offset+=textOf(t).length}for(const m of Array.from(full.matchAll(/\{\{([A-Z0-9_]+)\}\}/g)).reverse()){if(values[m[1]]===undefined)continue;const begin=m.index,end=begin+m[0].length,first=ts.findIndex((t,i)=>starts[i]<=begin&&begin<starts[i]+textOf(t).length),last=ts.findIndex((t,i)=>starts[i]<end&&end<=starts[i]+textOf(t).length);if(first<0||last<0)fail('Cannot merge a template field.');const left=textOf(ts[first]).slice(0,begin-starts[first]),right=textOf(ts[last]).slice(end-starts[last]);setText(ts[first],left+String(values[m[1]])+(first===last?right:''));if(first!==last){for(let i=first+1;i<last;i++)setText(ts[i],'');setText(ts[last],right)}changed=true}}if(changed){for(const run of descendants(tree,'r')){const out=[];for(const t of run.elements||[]){if(localName(t.name)==='t'&&textOf(t).includes('\n')){const parts=textOf(t).split('\n');for(let i=0;i<parts.length;i++){if(i)out.push({type:'element',name:'w:br'});out.push({...t,attributes:{...t.attributes,'xml:space':'preserve'},elements:[{type:'text',text:parts[i]}]})}}else out.push(t)}run.elements=out}z.file(name,js2xml(tree,{compact:false}))}}return z.generateAsync({type:'uint8array',compression:'DEFLATE'})}
export async function reportPack(config,records,report,bucket){const z=new JSZip(),values=reportTokens(config,report);z.file('report_data.json',JSON.stringify(report,null,2));for(const kind of ['summary','table5','table51']){const docs=(records.document||[]).filter(d=>d.kind===kind&&d.unit===report.unit&&(!d.effective||d.effective<=report.end)).sort((a,b)=>(a.at||'').localeCompare(b.at||''));const d=docs.at(-1);if(!d)fail('Upload the Summary, Table 5 and Table 5.1 Word templates for this unit before export.');const blob=await bucket.get(d.blob_key);if(!blob)fail('A report template is unavailable. Upload it again or contact the administrator.');z.file(`${report.year}_${report.period}_${kind}.docx`,await fillWord(new Uint8Array(await blob.arrayBuffer()),values))}return z.generateAsync({type:'uint8array',compression:'DEFLATE'})}
